apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    namespace: default
spec:
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  # 여러분의 image 주소를 입력해주세요.
                  image: idock.daumkakao.io/service-security/hunter-external:dev
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: krampoline
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend
---
#Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app.kubernetes.io/managed-by: kargocd
  name: krampoline
  namespace: default
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: krampoline
              servicePort: 8080
              path: /
              pathType: Prefix
