apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
    namespace: default
spec:
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  # 여러분의 image 주소를 입력해주세요.
                  image: krmp-d2hub-idock.9rum.cc/dev-test/repo_d6dce6ccda23
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 8080
